### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by nohwnd** [taicho/todo-plus#2]
I installed the extension and there are no todos in the explorer. I have a folder and a file todo.js open in which this text is saved, but no TODOs are detected. What am I doing wrong? 

```
//todo: hello

#todo: hello2

'todo: hello
```

**Comment by taicho** [comment]
@nohwnd I should have included a better example in the README. The word `TODO` must be capitalized and must be contained in a comment (line or block) approriate for the programming language the file is written in, in order for the extension to pick it up:

TypeScript/JavaScript Example:
```js
// TODO: Need to do this
```
